language: node_js
_aliases:
  - &node-prod
    # This is the NodeJS version we run in production.
    node_js: '8'
  - &node-next
    # This is the next NodeJS version we will support.
    node_js: '10'

cache:
  yarn: true

# See: https://github.com/mozilla/addons-frontend/issues/3034
install: yarn install --pure-lockfile

matrix:
  fast_finish: true

jobs:
  include:
    - name: unit tests (node@production)
      <<: *node-prod
      script: yarn test
    - name: unit tests (node@next)
      <<: *node-next
      script: yarn test
    - name: prettier
      <<: *node-prod
      script: yarn prettier-ci
